root: true
parser: babel-eslint
extends:
  - airbnb
  - prettier
plugins:
  - prettier

rules:
  ###########
  # PLUGINS #
  ###########
  import/prefer-default-export: 0

  ###########
  # BUILTIN #
  ###########
  no-param-reassign: 0
  no-underscore-dangle: 0
  no-plusplus: 0

  ###########
  # SPECIAL #
  ###########
  prettier/prettier:
    - error
    - singleQuote: true
      trailingComma: es5
      semi: false
